source ~/.dotfiles/zsh/antigen.zsh

load_files() {
	declare -a FILES=(
		${HOME}/.dotfiles/zsh/aliases.zsh
		${HOME}/.dotfiles/zsh/exports.zsh
		${HOME}/.dotfiles/zsh/functions.zsh
		${HOME}/.dotfiles/zsh/helpers.zsh
	)

	for x in "${FILES[@]}"; do
		[[ -f "$x" ]] && source "$x"
	done
}

# Source other files
load_files

export PATH="/usr/local/sbin:$PATH"

# Append history as commands are executed
setopt inc_append_history

# Don't save duplicates
setopt hist_ignore_all_dups

# Treat #, ~, and ^ as part of patterns for filename generation
setopt extended_glob

# Load antigen packages
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

antigen apply

unset load_files
